name: Sync to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN_SYNC }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          git clone https://akshat18:$HF_TOKEN@huggingface.co/spaces/akshat18/SAGE hf-space

          rsync -av --delete \
            --exclude ".git" \
            --exclude ".github" \
            ./ hf-space/

          cd hf-space

          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Auto sync from GitHub"

          git push